================================================
``makefile`` -- Makefile Buildcloth Syntax Layer
================================================

.. automodule:: makefile
   :members:
   :private-members:
