================================================
``makefile`` -- Makefile Buildcloth Syntax Layer
================================================

.. automodule:: makefile
   :members:
   :undoc-members:
